# Place a copy of this config to ~/.aerospace.toml
# After that, you can edit ~/.aerospace.toml to your liking

# Config version for compatibility and deprecations
# Fallback value (if you omit the key): config-version = 1
config-version = 2

# You can use it to add commands that run after AeroSpace startup.
# Available commands : https://nikitabobko.github.io/AeroSpace/commands
after-startup-command = []

# Start AeroSpace at login
start-at-login = false

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 15

# Possible values: tiles|accordion
default-root-container-layout = 'accordion'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Mouse follows focus when focused monitor changes
# Drop it from your config, if you don't like this behavior
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
# Fallback value (if you omit the key): on-focused-monitor-changed = []
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# You can effectively turn off macOS "Hide application" (cmd-h) feature by toggling this flag
# Useful if you don't use this macOS feature, but accidentally hit cmd-h or cmd-alt-h key
# Also see: https://nikitabobko.github.io/AeroSpace/goodies#disable-hide-app
automatically-unhide-macos-hidden-apps = false

# List of workspaces that should stay alive even when they contain no windows,
# even when they are invisible.
# This config version is only available since 'config-version = 2'
# Fallback value (if you omit the key): persistent-workspaces = []
persistent-workspaces = []

# A callback that runs every time binding mode changes
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# See: https://nikitabobko.github.io/AeroSpace/commands#mode
on-mode-changed = []

# Possible values: (qwerty|dvorak|colemak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
[key-mapping]
preset = 'qwerty'

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See:
#                 https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
inner.horizontal = 3
inner.vertical = 3
outer.left = 0
outer.bottom = 0
outer.top = 0
outer.right = 0

# 'main' binding mode declaration
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# 'main' binding mode must be always presented
# Fallback value (if you omit the key): mode.main.binding = {}
[mode.main.binding]

# See: https://nikitabobko.github.io/AeroSpace/commands#layout
alt-ctrl-cmd-slash = 'layout tiles horizontal vertical'
alt-ctrl-cmd-comma = 'layout accordion horizontal vertical'

# See: https://nikitabobko.github.io/AeroSpace/commands#focus
alt-ctrl-cmd-h = 'focus left'
alt-ctrl-cmd-j = 'focus down'
alt-ctrl-cmd-k = 'focus up'
alt-ctrl-cmd-l = 'focus right'

# See: https://nikitabobko.github.io/AeroSpace/commands#move
alt-ctrl-cmd-shift-h = 'move left'
alt-ctrl-cmd-shift-j = 'move down'
alt-ctrl-cmd-shift-k = 'move up'
alt-ctrl-cmd-shift-l = 'move right'

# See: https://nikitabobko.github.io/AeroSpace/commands#resize
alt-ctrl-cmd-minus = 'resize smart -50'
alt-ctrl-cmd-equal = 'resize smart +50'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace
alt-ctrl-cmd-1 = 'workspace 1'
alt-ctrl-cmd-2 = 'workspace 2'
alt-ctrl-cmd-3 = 'workspace 3'
alt-ctrl-cmd-4 = 'workspace 4'
alt-ctrl-cmd-5 = 'workspace 5'
alt-ctrl-cmd-6 = 'workspace 6'
alt-ctrl-cmd-7 = 'workspace 7'
alt-ctrl-cmd-8 = 'workspace 8'
alt-ctrl-cmd-9 = 'workspace 9'
alt-ctrl-cmd-a = 'workspace A'
alt-ctrl-cmd-b = 'workspace B'
alt-ctrl-cmd-c = 'workspace C'
alt-ctrl-cmd-d = 'workspace D'
alt-ctrl-cmd-e = 'workspace E'
alt-ctrl-cmd-f = 'workspace F'
alt-ctrl-cmd-g = 'workspace G'
alt-ctrl-cmd-i = 'workspace I'
alt-ctrl-cmd-m = 'workspace M'
alt-ctrl-cmd-n = 'workspace N'
alt-ctrl-cmd-o = 'workspace O'
alt-ctrl-cmd-p = 'workspace P'
alt-ctrl-cmd-q = 'workspace Q'
alt-ctrl-cmd-r = 'workspace R'
alt-ctrl-cmd-s = 'workspace S'
alt-ctrl-cmd-t = 'workspace T'
alt-ctrl-cmd-u = 'workspace U'
# alt-ctrl-cmd-v = 'workspace V'
alt-ctrl-cmd-w = 'workspace W'
alt-ctrl-cmd-x = 'workspace X'
alt-ctrl-cmd-y = 'workspace Y'
alt-ctrl-cmd-z = 'workspace Z'

# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
alt-ctrl-cmd-shift-1 = 'move-node-to-workspace 1'
alt-ctrl-cmd-shift-2 = 'move-node-to-workspace 2'
alt-ctrl-cmd-shift-3 = 'move-node-to-workspace 3'
alt-ctrl-cmd-shift-4 = 'move-node-to-workspace 4'
alt-ctrl-cmd-shift-5 = 'move-node-to-workspace 5'
alt-ctrl-cmd-shift-6 = 'move-node-to-workspace 6'
alt-ctrl-cmd-shift-7 = 'move-node-to-workspace 7'
alt-ctrl-cmd-shift-8 = 'move-node-to-workspace 8'
alt-ctrl-cmd-shift-9 = 'move-node-to-workspace 9'
alt-ctrl-cmd-shift-a = 'move-node-to-workspace A'
alt-ctrl-cmd-shift-b = 'move-node-to-workspace B'
alt-ctrl-cmd-shift-c = 'move-node-to-workspace C'
alt-ctrl-cmd-shift-d = 'move-node-to-workspace D'
alt-ctrl-cmd-shift-e = 'move-node-to-workspace E'
alt-ctrl-cmd-shift-f = 'move-node-to-workspace F'
alt-ctrl-cmd-shift-g = 'move-node-to-workspace G'
alt-ctrl-cmd-shift-i = 'move-node-to-workspace I'
alt-ctrl-cmd-shift-m = 'move-node-to-workspace M'
alt-ctrl-cmd-shift-n = 'move-node-to-workspace N'
alt-ctrl-cmd-shift-o = 'move-node-to-workspace O'
alt-ctrl-cmd-shift-p = 'move-node-to-workspace P'
alt-ctrl-cmd-shift-q = 'move-node-to-workspace Q'
alt-ctrl-cmd-shift-r = 'move-node-to-workspace R'
alt-ctrl-cmd-shift-s = 'move-node-to-workspace S'
alt-ctrl-cmd-shift-t = 'move-node-to-workspace T'
alt-ctrl-cmd-shift-u = 'move-node-to-workspace U'
# alt-ctrl-cmd-shift-v = 'move-node-to-workspace V'
alt-ctrl-cmd-shift-w = 'move-node-to-workspace W'
alt-ctrl-cmd-shift-x = 'move-node-to-workspace X'
alt-ctrl-cmd-shift-y = 'move-node-to-workspace Y'
alt-ctrl-cmd-shift-z = 'move-node-to-workspace Z'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
alt-ctrl-cmd-tab = 'workspace-back-and-forth'
# See: https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor
alt-ctrl-cmd-shift-tab = 'move-workspace-to-monitor --wrap-around next'

# See: https://nikitabobko.github.io/AeroSpace/commands#mode
alt-ctrl-cmd-shift-semicolon = 'mode service'

# Fullscreen
alt-ctrl-cmd-enter = 'fullscreen'

# 'service' binding mode declaration.
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] # Reset layout
f = [
  'layout floating tiling',
  'mode main',
] # Toggle between floating and tiling layout
backspace = ['close-all-windows-but-current', 'mode main']

alt-ctrl-cmd-shift-h = ['join-with left', 'mode main']
alt-ctrl-cmd-shift-j = ['join-with down', 'mode main']
alt-ctrl-cmd-shift-k = ['join-with up', 'mode main']
alt-ctrl-cmd-shift-l = ['join-with right', 'mode main']

# Apps with dedicated workspace

# Calendar
[[on-window-detected]]
if.app-id = "com.cron.electron"
run = "move-node-to-workspace C"

# Text Editor
[[on-window-detected]]
if.app-id = "com.microsoft.VSCode"
run = "move-node-to-workspace E"

# Mail/Messaging
[[on-window-detected]]
if.app-id = "com.apple.mail"
run = "move-node-to-workspace M"

[[on-window-detected]]
if.app-id = "jp.naver.line.mac"
run = "move-node-to-workspace M"

# Obsidian
[[on-window-detected]]
if.app-id = "md.obsidian"
run = "move-node-to-workspace O"

# Reminder
[[on-window-detected]]
if.app-id = "com.culturedcode.ThingsMac"
run = "move-node-to-workspace R"

# Terminal
[[on-window-detected]]
if.app-id = "com.mitchellh.ghostty"
run = "move-node-to-workspace T"

# Music
[[on-window-detected]]
if.app-id = "com.apple.Music"
run = "move-node-to-workspace U"

# Web
[[on-window-detected]]
if.app-id = "app.zen-browser.zen"
run = "move-node-to-workspace W"

# Zotero
[[on-window-detected]]
if.app-id = "org.zotero.zotero-beta"
run = "move-node-to-workspace Z"

# Finder window always floats
[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = 'layout floating'
